- name: 'gcr.io/cloud-builders/gcloud'
args:
  — functions
  — deploy
  — — runtime=nodejs10
  — — trigger-http
  — — entry-point=showMessage # Function entry point
  — vladsFirstCloudF # Function name
waitFor: ['_']
id: 'deploying-vlads-cloud-functions'

