id: 'deploying-vlads-cloud-functions'
steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
    dir: 'src'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'vladsFirstCloudF', 'trigger-http', '--runtime', 'nodejs10', '--entry-point', 'showMessage']
    dir: 'src'
